FROM vhiveease/python-slim
# FROM python:3.11-slim
# FROM python

ENV name=name

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]






# layer 1
# layer 2
# layer 3
# layer 4
# layer 5
# layer6
# layer 7