name: lambda build
# This sets the name of the workflow to "Terraform Deploy"

on:
  
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
      TERRAFORM_VER: 1.8.1
      TERRAFORM_PATH:  multi-lambda/python-lambda/infra

      # Path to your Terraform files

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.1"

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init

      - name: Terraform formatting check
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform fmt -check
      # - name: Checkov
      #   uses: bridgecrewio/checkov-action@v12
      #   with:
      #     directory: ${{ env.TERRAFORM_PATH }}
      #     quiet: true
      #     skip_check: CKV_AWS_338,CKV_AWS_51

      # - name: Terraform Plan
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform plan

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform apply   -auto-approve

      ## Only when destroying 

      # - name: terrafom destroy setup
      #   working-directory: ${{ env.TERRAFORM_PATH }}
      #   run: terraform destroy  -auto-approve