version: '3.8'

services:
  app:
    build: . # This will build the container from the Dockerfile stored locally.
    ports:
      - "4000:5000"
    networks:
      - test_network 
    depends_on:
      db:
        condition: service_healthy   # will wait for db to be ready

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_network
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:

networks:
  test_network: